from as7265x import AS7265X
from smbus import SMBus
import time
import sys

i2c = SMBus(1)
sensor = AS7265X(i2c)

if not sensor.begin():
    print("Error : Device not connected.")
    sys.exit()

print("SoftReset!")
sensor.softReset()
time.sleep(2)

print("Device type:{:X}".format(sensor.getDeviceType()))
print("HW Version:{:X}".format(sensor.getHardwareVersion()))
print("FW Major version:{:d}".format(sensor.getMajorFirmwareVersion()))
print("FW Patch version:{:d}".format(sensor.getPatchFirmwareVersion()))
print("FW Build version:{:d}".format(sensor.getBuildFirmwareVersion()))
print("Temperature-AS72651:{:d}".format(sensor.getTemperature(0)))
print("Temperature-AS72652:{:d}".format(sensor.getTemperature(1)))
print("Temperature-AS72653:{:d}".format(sensor.getTemperature(3)))
print("Average temperature:{:.2f}".format(sensor.getTemperatureAverage()))

print("====================")
print("takeMeasurements")
print("    Mode:6ch One-Shot")
print("    Gain:64X")
print("Calibrated value (Raw value)")
sensor.takeMeasurements()
print("A:{:.2f} ({:.2f})".format(sensor.getCalibratedA(), sensor.getA()))
print("B:{:.2f} ({:.2f})".format(sensor.getCalibratedB(), sensor.getB()))
print("C:{:.2f} ({:.2f})".format(sensor.getCalibratedC(), sensor.getC()))
print("D:{:.2f} ({:.2f})".format(sensor.getCalibratedD(), sensor.getD()))
print("E:{:.2f} ({:.2f})".format(sensor.getCalibratedE(), sensor.getE()))
print("F:{:.2f} ({:.2f})".format(sensor.getCalibratedF(), sensor.getF()))
print("G:{:.2f} ({:.2f})".format(sensor.getCalibratedG(), sensor.getG()))
print("H:{:.2f} ({:.2f})".format(sensor.getCalibratedH(), sensor.getH()))
print("I:{:.2f} ({:.2f})".format(sensor.getCalibratedI(), sensor.getI()))
print("J:{:.2f} ({:.2f})".format(sensor.getCalibratedJ(), sensor.getJ()))
print("K:{:.2f} ({:.2f})".format(sensor.getCalibratedK(), sensor.getK()))
print("L:{:.2f} ({:.2f})".format(sensor.getCalibratedL(), sensor.getL()))
print("R:{:.2f} ({:.2f})".format(sensor.getCalibratedR(), sensor.getR()))
print("S:{:.2f} ({:.2f})".format(sensor.getCalibratedS(), sensor.getS()))
print("T:{:.2f} ({:.2f})".format(sensor.getCalibratedT(), sensor.getT()))
print("U:{:.2f} ({:.2f})".format(sensor.getCalibratedU(), sensor.getU()))
print("V:{:.2f} ({:.2f})".format(sensor.getCalibratedV(), sensor.getV()))
print("W:{:.2f} ({:.2f})".format(sensor.getCalibratedW(), sensor.getW()))


print("====================")
print("takeMeasurementsWithBulb")
print("    Mode:6ch One-Shot")
print("    Gain:64X")
print("Calibrated value (Raw value)")
sensor.takeMeasurementsWithBulb()
print("A:{:.2f} ({:.2f})".format(sensor.getCalibratedA(), sensor.getA()))
print("B:{:.2f} ({:.2f})".format(sensor.getCalibratedB(), sensor.getB()))
print("C:{:.2f} ({:.2f})".format(sensor.getCalibratedC(), sensor.getC()))
print("D:{:.2f} ({:.2f})".format(sensor.getCalibratedD(), sensor.getD()))
print("E:{:.2f} ({:.2f})".format(sensor.getCalibratedE(), sensor.getE()))
print("F:{:.2f} ({:.2f})".format(sensor.getCalibratedF(), sensor.getF()))
print("G:{:.2f} ({:.2f})".format(sensor.getCalibratedG(), sensor.getG()))
print("H:{:.2f} ({:.2f})".format(sensor.getCalibratedH(), sensor.getH()))
print("I:{:.2f} ({:.2f})".format(sensor.getCalibratedI(), sensor.getI()))
print("J:{:.2f} ({:.2f})".format(sensor.getCalibratedJ(), sensor.getJ()))
print("K:{:.2f} ({:.2f})".format(sensor.getCalibratedK(), sensor.getK()))
print("L:{:.2f} ({:.2f})".format(sensor.getCalibratedL(), sensor.getL()))
print("R:{:.2f} ({:.2f})".format(sensor.getCalibratedR(), sensor.getR()))
print("S:{:.2f} ({:.2f})".format(sensor.getCalibratedS(), sensor.getS()))
print("T:{:.2f} ({:.2f})".format(sensor.getCalibratedT(), sensor.getT()))
print("U:{:.2f} ({:.2f})".format(sensor.getCalibratedU(), sensor.getU()))
print("V:{:.2f} ({:.2f})".format(sensor.getCalibratedV(), sensor.getV()))
print("W:{:.2f} ({:.2f})".format(sensor.getCalibratedW(), sensor.getW()))

print("====================")
print("takeMeasurementsWithBulb")
print("    Mode:6ch One-Shot")
print("    Gain:1X")
print("Calibrated value (Raw value)")
sensor.setGain(0)
sensor.takeMeasurementsWithBulb()
print("A:{:.2f} ({:.2f})".format(sensor.getCalibratedA(), sensor.getA()))
print("B:{:.2f} ({:.2f})".format(sensor.getCalibratedB(), sensor.getB()))
print("C:{:.2f} ({:.2f})".format(sensor.getCalibratedC(), sensor.getC()))
print("D:{:.2f} ({:.2f})".format(sensor.getCalibratedD(), sensor.getD()))
print("E:{:.2f} ({:.2f})".format(sensor.getCalibratedE(), sensor.getE()))
print("F:{:.2f} ({:.2f})".format(sensor.getCalibratedF(), sensor.getF()))
print("G:{:.2f} ({:.2f})".format(sensor.getCalibratedG(), sensor.getG()))
print("H:{:.2f} ({:.2f})".format(sensor.getCalibratedH(), sensor.getH()))
print("I:{:.2f} ({:.2f})".format(sensor.getCalibratedI(), sensor.getI()))
print("J:{:.2f} ({:.2f})".format(sensor.getCalibratedJ(), sensor.getJ()))
print("K:{:.2f} ({:.2f})".format(sensor.getCalibratedK(), sensor.getK()))
print("L:{:.2f} ({:.2f})".format(sensor.getCalibratedL(), sensor.getL()))
print("R:{:.2f} ({:.2f})".format(sensor.getCalibratedR(), sensor.getR()))
print("S:{:.2f} ({:.2f})".format(sensor.getCalibratedS(), sensor.getS()))
print("T:{:.2f} ({:.2f})".format(sensor.getCalibratedT(), sensor.getT()))
print("U:{:.2f} ({:.2f})".format(sensor.getCalibratedU(), sensor.getU()))
print("V:{:.2f} ({:.2f})".format(sensor.getCalibratedV(), sensor.getV()))
print("W:{:.2f} ({:.2f})".format(sensor.getCalibratedW(), sensor.getW()))

print("====================")
print("takeMeasurementsWithBulb")
print("    Mode:4ch (R,W,J,L,D,F will be Zero)")
print("    Gain:64X")
print("Calibrated value (Raw value)")
sensor.setGain(3)
sensor.setMeasurementMode(0)
sensor.takeMeasurementsWithBulb()
print("A:{:.2f} ({:.2f})".format(sensor.getCalibratedA(), sensor.getA()))
print("B:{:.2f} ({:.2f})".format(sensor.getCalibratedB(), sensor.getB()))
print("C:{:.2f} ({:.2f})".format(sensor.getCalibratedC(), sensor.getC()))
print("D:{:.2f} ({:.2f})".format(sensor.getCalibratedD(), sensor.getD()))
print("E:{:.2f} ({:.2f})".format(sensor.getCalibratedE(), sensor.getE()))
print("F:{:.2f} ({:.2f})".format(sensor.getCalibratedF(), sensor.getF()))
print("G:{:.2f} ({:.2f})".format(sensor.getCalibratedG(), sensor.getG()))
print("H:{:.2f} ({:.2f})".format(sensor.getCalibratedH(), sensor.getH()))
print("I:{:.2f} ({:.2f})".format(sensor.getCalibratedI(), sensor.getI()))
print("J:{:.2f} ({:.2f})".format(sensor.getCalibratedJ(), sensor.getJ()))
print("K:{:.2f} ({:.2f})".format(sensor.getCalibratedK(), sensor.getK()))
print("L:{:.2f} ({:.2f})".format(sensor.getCalibratedL(), sensor.getL()))
print("R:{:.2f} ({:.2f})".format(sensor.getCalibratedR(), sensor.getR()))
print("S:{:.2f} ({:.2f})".format(sensor.getCalibratedS(), sensor.getS()))
print("T:{:.2f} ({:.2f})".format(sensor.getCalibratedT(), sensor.getT()))
print("U:{:.2f} ({:.2f})".format(sensor.getCalibratedU(), sensor.getU()))
print("V:{:.2f} ({:.2f})".format(sensor.getCalibratedV(), sensor.getV()))
print("W:{:.2f} ({:.2f})".format(sensor.getCalibratedW(), sensor.getW()))

print("====================")
print("takeMeasurements Continuous")
print("    Mode:6ch continuous")
print("    Gain:64X")
print("    IntegrationCycle:1")
print("Calibrated value (Raw value)")
sensor.setMeasurementMode(2)
sensor.enableBulb(0)
sensor.enableBulb(1)
sensor.enableBulb(2)
sensor.disableIndicator()
sensor.setIntegrationCycles(1)
for i in range(5):
    while not sensor.dataAvailable():
        pass
    print("----Loop {:d}----".format(i))
    print("A:{:.2f} ({:.2f})".format(sensor.getCalibratedA(), sensor.getA()))
    print("B:{:.2f} ({:.2f})".format(sensor.getCalibratedB(), sensor.getB()))
    print("C:{:.2f} ({:.2f})".format(sensor.getCalibratedC(), sensor.getC()))
    print("D:{:.2f} ({:.2f})".format(sensor.getCalibratedD(), sensor.getD()))
    print("E:{:.2f} ({:.2f})".format(sensor.getCalibratedE(), sensor.getE()))
    print("F:{:.2f} ({:.2f})".format(sensor.getCalibratedF(), sensor.getF()))
    print("G:{:.2f} ({:.2f})".format(sensor.getCalibratedG(), sensor.getG()))
    print("H:{:.2f} ({:.2f})".format(sensor.getCalibratedH(), sensor.getH()))
    print("I:{:.2f} ({:.2f})".format(sensor.getCalibratedI(), sensor.getI()))
    print("J:{:.2f} ({:.2f})".format(sensor.getCalibratedJ(), sensor.getJ()))
    print("K:{:.2f} ({:.2f})".format(sensor.getCalibratedK(), sensor.getK()))
    print("L:{:.2f} ({:.2f})".format(sensor.getCalibratedL(), sensor.getL()))
    print("R:{:.2f} ({:.2f})".format(sensor.getCalibratedR(), sensor.getR()))
    print("S:{:.2f} ({:.2f})".format(sensor.getCalibratedS(), sensor.getS()))
    print("T:{:.2f} ({:.2f})".format(sensor.getCalibratedT(), sensor.getT()))
    print("U:{:.2f} ({:.2f})".format(sensor.getCalibratedU(), sensor.getU()))
    print("V:{:.2f} ({:.2f})".format(sensor.getCalibratedV(), sensor.getV()))
    print("W:{:.2f} ({:.2f})".format(sensor.getCalibratedW(), sensor.getW()))
sensor.disableBulb(0)
sensor.disableBulb(1)
sensor.disableBulb(2)

